version: '3.7'
services:
  hotel:
    container_name: hotel
    build:
      context: hotel
      dockerfile: Dockerfile
      args:
        PUBLIC_URL: /hotel/
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      server-vpn:

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
      args:
        PUBLIC_URL: /client/
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      server-vpn:

  postgres:
    restart: always
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "bookly", "-U", "bookly" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      server-vpn:

  init-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile.psql
    entrypoint: ["psql","-f","./load.sql"]
    volumes:
      - ./postgres/migration:/usr/local/bin
    environment:
      PGPASSWORD: bookly
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: bookly
      PGDATABASE: bookly
    networks:
      server-vpn:

  offer-service:
    container_name: offer-service
    build:
      context: server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: offer-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      - server-vpn
  hotel-service:
    container_name:  hotel-service
    build:
      context: server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: hotel-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      - server-vpn

  user-service:
    container_name: user-service
    build:
      context: server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      - server-vpn

  api-gateway:
    image: nginx:stable-alpine
    container_name: api-gateway-nginx
    ports:
    - 8080:80
    volumes:
      - ./api-gateway/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      server-vpn:

  auth-service:
    container_name: auth-service
    build:
      context: server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      server-vpn:

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/swagger-api.json
    networks:
      server-vpn:

networks:
  server-vpn:

