version: '3.7'
services:
  hotel:
    container_name: hotel
    build:
      context: hotel
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    restart: always
    build:
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "bookly", "-U", "bookly" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    networks:
      server-vpn:

  offer-service:
    container_name: offer-service
    build:
      context: server
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: offer-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookly
      POSTGRES_PASSWORD: bookly
      POSTGRES_DATABASE: bookly
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - server-vpn

  api-gateway:
    image: nginx:stable-alpine
    container_name: api-gateway-nginx
    ports:
    - 24502:80
    volumes:
      - ./api-gateway/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - offer-service
    networks:
      server-vpn:


networks:
  server-vpn:

