// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bookly/room.go

// Package mock_bookly is a generated GoMock package.
package mock_bookly

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	bookly "github.com/pw-software-engineering/b-team/server/pkg/bookly"
)

// MockRoomStorage is a mock of RoomStorage interface.
type MockRoomStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStorageMockRecorder
}

// MockRoomStorageMockRecorder is the mock recorder for MockRoomStorage.
type MockRoomStorageMockRecorder struct {
	mock *MockRoomStorage
}

// NewMockRoomStorage creates a new mock instance.
func NewMockRoomStorage(ctrl *gomock.Controller) *MockRoomStorage {
	mock := &MockRoomStorage{ctrl: ctrl}
	mock.recorder = &MockRoomStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStorage) EXPECT() *MockRoomStorageMockRecorder {
	return m.recorder
}

// AddLinkWithRoomAndOffer mocks base method.
func (m *MockRoomStorage) AddLinkWithRoomAndOffer(ctx context.Context, offerID, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLinkWithRoomAndOffer", ctx, offerID, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLinkWithRoomAndOffer indicates an expected call of AddLinkWithRoomAndOffer.
func (mr *MockRoomStorageMockRecorder) AddLinkWithRoomAndOffer(ctx, offerID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLinkWithRoomAndOffer", reflect.TypeOf((*MockRoomStorage)(nil).AddLinkWithRoomAndOffer), ctx, offerID, roomID)
}

// CreateRoom mocks base method.
func (m *MockRoomStorage) CreateRoom(ctx context.Context, room bookly.Room, hotelID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room, hotelID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomStorageMockRecorder) CreateRoom(ctx, room, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomStorage)(nil).CreateRoom), ctx, room, hotelID)
}

// DeleteLinkWithRoomAndOffer mocks base method.
func (m *MockRoomStorage) DeleteLinkWithRoomAndOffer(ctx context.Context, offerID, roomID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLinkWithRoomAndOffer", ctx, offerID, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLinkWithRoomAndOffer indicates an expected call of DeleteLinkWithRoomAndOffer.
func (mr *MockRoomStorageMockRecorder) DeleteLinkWithRoomAndOffer(ctx, offerID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLinkWithRoomAndOffer", reflect.TypeOf((*MockRoomStorage)(nil).DeleteLinkWithRoomAndOffer), ctx, offerID, roomID)
}

// DeleteRoom mocks base method.
func (m *MockRoomStorage) DeleteRoom(ctx context.Context, roomID, hotelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID, hotelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomStorageMockRecorder) DeleteRoom(ctx, roomID, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomStorage)(nil).DeleteRoom), ctx, roomID, hotelID)
}

// GetAllHotelRooms mocks base method.
func (m *MockRoomStorage) GetAllHotelRooms(ctx context.Context, hotelID int64) ([]*bookly.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHotelRooms", ctx, hotelID)
	ret0, _ := ret[0].([]*bookly.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHotelRooms indicates an expected call of GetAllHotelRooms.
func (mr *MockRoomStorageMockRecorder) GetAllHotelRooms(ctx, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHotelRooms", reflect.TypeOf((*MockRoomStorage)(nil).GetAllHotelRooms), ctx, hotelID)
}

// GetRoom mocks base method.
func (m *MockRoomStorage) GetRoom(ctx context.Context, roomID int64) (bookly.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(bookly.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomStorageMockRecorder) GetRoom(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomStorage)(nil).GetRoom), ctx, roomID)
}

// GetRoomByName mocks base method.
func (m *MockRoomStorage) GetRoomByName(ctx context.Context, roomNumber string, hotelID int64) (bookly.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByName", ctx, roomNumber, hotelID)
	ret0, _ := ret[0].(bookly.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByName indicates an expected call of GetRoomByName.
func (mr *MockRoomStorageMockRecorder) GetRoomByName(ctx, roomNumber, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByName", reflect.TypeOf((*MockRoomStorage)(nil).GetRoomByName), ctx, roomNumber, hotelID)
}

// IsExistLinkWithRoomAndOffer mocks base method.
func (m *MockRoomStorage) IsExistLinkWithRoomAndOffer(ctx context.Context, offerID, roomID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistLinkWithRoomAndOffer", ctx, offerID, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistLinkWithRoomAndOffer indicates an expected call of IsExistLinkWithRoomAndOffer.
func (mr *MockRoomStorageMockRecorder) IsExistLinkWithRoomAndOffer(ctx, offerID, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistLinkWithRoomAndOffer", reflect.TypeOf((*MockRoomStorage)(nil).IsExistLinkWithRoomAndOffer), ctx, offerID, roomID)
}

// IsRoomBelongToHotel mocks base method.
func (m *MockRoomStorage) IsRoomOwnedByHotel(ctx context.Context, roomID, hotelID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomOwnedByHotel", ctx, roomID, hotelID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomBelongToHotel indicates an expected call of IsRoomBelongToHotel.
func (mr *MockRoomStorageMockRecorder) IsRoomBelongToHotel(ctx, roomID, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomOwnedByHotel", reflect.TypeOf((*MockRoomStorage)(nil).IsRoomOwnedByHotel), ctx, roomID, hotelID)
}

// OffersRelatedWithRoom mocks base method.
func (m *MockRoomStorage) GetOffersRelatedWithRoom(ctx context.Context, roomID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOffersRelatedWithRoom", ctx, roomID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OffersRelatedWithRoom indicates an expected call of OffersRelatedWithRoom.
func (mr *MockRoomStorageMockRecorder) OffersRelatedWithRoom(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOffersRelatedWithRoom", reflect.TypeOf((*MockRoomStorage)(nil).GetOffersRelatedWithRoom), ctx, roomID)
}

// RoomsRelatedWithOffer mocks base method.
func (m *MockRoomStorage) GetRoomsRelatedWithOffer(ctx context.Context, offerID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomsRelatedWithOffer", ctx, offerID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomsRelatedWithOffer indicates an expected call of RoomsRelatedWithOffer.
func (mr *MockRoomStorageMockRecorder) RoomsRelatedWithOffer(ctx, offerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomsRelatedWithOffer", reflect.TypeOf((*MockRoomStorage)(nil).GetRoomsRelatedWithOffer), ctx, offerID)
}

// MockRoomService is a mock of RoomService interface.
type MockRoomService struct {
	ctrl     *gomock.Controller
	recorder *MockRoomServiceMockRecorder
}

// MockRoomServiceMockRecorder is the mock recorder for MockRoomService.
type MockRoomServiceMockRecorder struct {
	mock *MockRoomService
}

// NewMockRoomService creates a new mock instance.
func NewMockRoomService(ctrl *gomock.Controller) *MockRoomService {
	mock := &MockRoomService{ctrl: ctrl}
	mock.recorder = &MockRoomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomService) EXPECT() *MockRoomServiceMockRecorder {
	return m.recorder
}

// AddRoomToOffer mocks base method.
func (m *MockRoomService) AddRoomToOffer(ctx context.Context, offerID, roomID, hotelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoomToOffer", ctx, offerID, roomID, hotelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoomToOffer indicates an expected call of AddRoomToOffer.
func (mr *MockRoomServiceMockRecorder) AddRoomToOffer(ctx, offerID, roomID, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoomToOffer", reflect.TypeOf((*MockRoomService)(nil).AddRoomToOffer), ctx, offerID, roomID, hotelID)
}

// CreateRoom mocks base method.
func (m *MockRoomService) CreateRoom(ctx context.Context, room bookly.Room, hotelID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room, hotelID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomServiceMockRecorder) CreateRoom(ctx, room, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomService)(nil).CreateRoom), ctx, room, hotelID)
}

// DeleteRoom mocks base method.
func (m *MockRoomService) DeleteRoom(ctx context.Context, roomID, hotelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID, hotelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomServiceMockRecorder) DeleteRoom(ctx, roomID, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomService)(nil).DeleteRoom), ctx, roomID, hotelID)
}

// DeleteRoomFromOffer mocks base method.
func (m *MockRoomService) DeleteRoomFromOffer(ctx context.Context, offerID, roomID, hotelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomFromOffer", ctx, offerID, roomID, hotelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomFromOffer indicates an expected call of DeleteRoomFromOffer.
func (mr *MockRoomServiceMockRecorder) DeleteRoomFromOffer(ctx, offerID, roomID, hotelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomFromOffer", reflect.TypeOf((*MockRoomService)(nil).DeleteRoomFromOffer), ctx, offerID, roomID, hotelID)
}

// GetAllHotelRooms mocks base method.
func (m *MockRoomService) GetAllHotelRooms(ctx context.Context, hotelID int64, pageNumber, pageSize int, filter string) ([]*bookly.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHotelRooms", ctx, hotelID, pageNumber, pageSize, filter)
	ret0, _ := ret[0].([]*bookly.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHotelRooms indicates an expected call of GetAllHotelRooms.
func (mr *MockRoomServiceMockRecorder) GetAllHotelRooms(ctx, hotelID, pageNumber, pageSize, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHotelRooms", reflect.TypeOf((*MockRoomService)(nil).GetAllHotelRooms), ctx, hotelID, pageNumber, pageSize, filter)
}

// GetRoomsRelatedWithOffer mocks base method.
func (m *MockRoomService) GetRoomsRelatedWithOffer(ctx context.Context, offerID, hotelID int64, pageNumber, pageSize int, filter string) ([]*bookly.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomsRelatedWithOffer", ctx, offerID, hotelID, pageNumber, pageSize, filter)
	ret0, _ := ret[0].([]*bookly.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomsRelatedWithOffer indicates an expected call of GetRoomsRelatedWithOffer.
func (mr *MockRoomServiceMockRecorder) GetRoomsRelatedWithOffer(ctx, offerID, hotelID, pageNumber, pageSize, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomsRelatedWithOffer", reflect.TypeOf((*MockRoomService)(nil).GetRoomsRelatedWithOffer), ctx, offerID, hotelID, pageNumber, pageSize, filter)
}
