apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: /swagger-ui/
            - name: API_URLS
              value: >-
                [
                {url:'swagger-api/openapi.json',name:'bookly'}
                ]
          volumeMounts:
            - name: swagger-api
              mountPath: /usr/share/nginx/html/swagger-api
      volumes:
        - name: swagger-api
          configMap:
            name: swagger-api
