name: Go

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.2

    - name: Build
      run: go build -v ./...
      working-directory: ./server

    - name: Test
      run: go test -v -short ./... #todo add database and run full integration tests in CI
      working-directory: ./server

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2.4.1
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.38.0
        working-directory: server
        skip-go-installation: true
        skip-pkg-cache: true
