name: DeployServerApps

on:
  repository_dispatch:
    types: [deploy]
  
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
    - 'server/**'

env:
  ACR_URL: 'powoeuwacr.azurecr.io'
  NAMESPACE: 'b'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACR_URL: ${{ env.ACR_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ACR_URL }}
        username: ${{ secrets.ACR_USER_ID }}
        password: ${{ secrets.ACR_USER_PASSWORD }}
    - name: Build and push server apps
      run: ./deploy/push-server-images.sh

